---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs:
  
  terraform: circleci/terraform@3.2.0



parameters:
  run_workflow_build:
    default: false
    type: boolean
  
workflows:
  deploy_infra_demo:
    when: <<pipeline.parameters.run_workflow_build>>
    jobs:
      plan-destroy:
        steps:
          - attach_workspace:
              at: .
          - run:
              context:terraformenv1
              name: terraform create destroy plan
              command: |
                terraform plan -destroy -out tfdestroy -var-file terraform.tfvars
          - persist_to_workspace:
              root: .
              paths:
                - .
          