---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs:
  
  terraform: circleci/terraform@3.2.0



parameters:
  run_workflow_build:
    default: false
    type: boolean
  
workflows:
  infra-deploy-source:
    when: <<pipeline.parameters.run_workflow_build>>
    jobs:
      plan-destroy:
        context : terraformenv1
        steps:
          - attach_workspace:
              at: .
          - run:
              name: terraform create destroy plan
              command: |
                terraform plan -destroy -out tfdestroy 
              root: .
              paths:
                - .
          